### ISSUE TITLE
Auth - Ensure superuser account is set up correct and linked as part of CI build

### ISSUE THREAD

**Issue by MarkAPhillips** [MarkAPhillips/auth-api#7]
Ensure lastname and firstname are filled in
Ensure User created is linked to an Account

Currently this has to be done manually via the admin when the account is setup

**Comment by MarkAPhillips** [comment]
Super user first name and last name now are assigned - this account will now be used for logging into the admin section only.
Need to create a test user account - need to determine how this can be created automatically

**Comment by mpconsultsai** [comment]
Initialisation is created using the initUser.py file in the build project - on the PROD env this tests whether these accounts already exist and only creates if they do not. 

On the DEV env as postgres is running inside a container - this is recreated every time the container is created
